### ISSUE TITLE
[BUG[ Bot throwing error every time a message is sent

### ISSUE THREAD

**Issue by Benroyz** [oadpoaw/bp-app-bot#2]
Hi, I've run into this error where if I send any messages with the bot viewing a channel, the error is thrown.

There is the error:
`[ERROR_TRACE]
Trace: Unhandled Rejection: TypeError: Cannot read property 'replace' of undefined
    at AppBotClient.escapeRegex (/app-bot/src/classes/AppBot.js:92:20)
    at MessageEvent.run (/app-bot/src/events/message.js:33:70)
    at AppBotClient.emit (events.js:198:13)
    at MessageCreateAction.handle (/app-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/app-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/app-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/app-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/app-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/app-bot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
    at Object.error (/app-bot/src/utils/Logger.js:19:12)
    at process.on (/app-bot/src/modules/ErrorHandler.js:4:23)
    at process.emit (events.js:198:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)
    at process._tickCallback (internal/process/next_tick.js:69:34)
[/ERROR_TRACE]
`
Is there a fix around this?

I am using this bot via the Docker container that I made if this'll help with the issue above.

P.S.: What is the bot's prefix?

**Comment by ehcac1024** [comment]
Oh, you didnt setup the bot prefix with
`DEFAULT_PREFIX=<botprefix>` in the `.env` file
i forgot to include this in the instructions somewhat.

**Comment by Benroyz** [comment]
Ok, it worked. Thanks. 

I ran into another problem the moment after the bot is back online - 
```
Error: Unexpected error occured : TypeError 
TypeError: fields.flat is not a function
```

I typed `!help` and `!apply staff` - which instantly deletes the messages as soon as possible. Are there any solutions on this?

EDIT: There is the bot log for this as well, so could it be related to SQLite?:
```
Executing (default): SELECT `app_type`, `applicants` FROM `applications` AS `applications` WHERE `applications`.`app_type` = 'staff';
Executing (default): SELECT `app_type`, `applicants` FROM `applications` AS `applications` WHERE `applications`.`app_type` = 'unban';
```

**Comment by ehcac1024** [comment]
Because you are running on an old version of nodejs

you can check your node's version via command line using:
`node -v`

Update to node v12 and above and that should do the trick!

EDIT: also yeah its related to sqlite

**Comment by Benroyz** [comment]
OK, it worked. I upgraded node.js to `v14.15.0` via dockefile. Everything is running smoothly so far now. 

Thanks!
